public class ViaCEP {
    @InvocableVariable
    public String cep;
    @InvocableVariable
    public String logradouro;
    @InvocableVariable
    public String complemento;
    @InvocableVariable
    public String bairro;
    @InvocableVariable
    public String localidade;
    @InvocableVariable
    public String uf;
    @InvocableVariable
    public String unidade;
    @InvocableVariable
    public String ibge;
    @InvocableVariable
    public String gia;
    @InvocableVariable
    public String ddd;
    @InvocableVariable
    public Boolean erro;
}